# Generated by Django 4.0.5 on 2022-07-27 12:14

import ELIB.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Author's Name")),
                ('added_on', models.DateField(default=django.utils.timezone.now, verbose_name='Added On')),
            ],
            options={
                'ordering': ['-added_on'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('cover', models.ImageField(default='./books/ELIB_book.wep3', upload_to=ELIB.models.get_file_path, verbose_name='Cover')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Safe Url')),
                ('added_on', models.DateField(default=django.utils.timezone.now, verbose_name='Added On')),
            ],
            options={
                'ordering': ['-added_on'],
            },
        ),
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Return Date')),
                ('borrowed', models.DateField(default=django.utils.timezone.now, verbose_name='Borrowed On')),
                ('fine', models.IntegerField(default=0, verbose_name='Fine')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
